services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command:
      - "/app/bin/rails"
      - "server"
      - "-b"
      - "0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
  redis:
    image: redis
